# Two Next.js apps:
#   * customer-web — public storefront, behind public ALB
#   * admin-web    — admin panel, behind internal ALB only
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-web
  namespace: shopcloud
  labels:
    app: customer-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customer-web
  template:
    metadata:
      labels:
        app: customer-web
    spec:
      containers:
        - name: customer-web
          image: REPLACE_ME/shopcloud/customer-web:dev
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: shopcloud-config
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 15
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: customer-web
  namespace: shopcloud
spec:
  selector:
    app: customer-web
  ports:
    - port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-web
  namespace: shopcloud
  labels:
    app: admin-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-web
  template:
    metadata:
      labels:
        app: admin-web
    spec:
      containers:
        - name: admin-web
          image: REPLACE_ME/shopcloud/admin-web:dev
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: shopcloud-config
          readinessProbe:
            httpGet:
              path: /
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 15
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: admin-web
  namespace: shopcloud
spec:
  selector:
    app: admin-web
  ports:
    - port: 80
      targetPort: 3001
