apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shopcloud
resources:
  - namespace.yaml
  - configmap.yaml
  - secret-example.yaml
  - frontend.yaml
  - catalog.yaml
  - cart.yaml
  - checkout.yaml
  - auth.yaml
  - admin.yaml
  - hpa.yaml
  - public-ingress.yaml
  - internal-admin-ingress.yaml