apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: public-shopcloud
  namespace: shopcloud
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /healthz
    alb.ingress.kubernetes.io/group.name: public-shopcloud
spec:
  rules:
    - host: shopcloud.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
    - host: api.shopcloud.example.com
      http:
        paths:
          - path: /products
            pathType: Prefix
            backend:
              service:
                name: catalog
                port:
                  number: 8001
          - path: /cart
            pathType: Prefix
            backend:
              service:
                name: cart
                port:
                  number: 8002
          - path: /checkout
            pathType: Prefix
            backend:
              service:
                name: checkout
                port:
                  number: 8003
          - path: /demo/login/customer
            pathType: Prefix
            backend:
              service:
                name: auth
                port:
                  number: 8004
          - path: /validate
            pathType: Prefix
            backend:
              service:
                name: auth
                port:
                  number: 8004