apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: patch-configmap.yaml
  - target:
      group: autoscaling
      version: v2
      kind: HorizontalPodAutoscaler
      name: catalog
    path: delete-hpa-catalog.yaml
  - target:
      group: autoscaling
      version: v2
      kind: HorizontalPodAutoscaler
      name: cart
    path: delete-hpa-cart.yaml
  - target:
      group: autoscaling
      version: v2
      kind: HorizontalPodAutoscaler
      name: checkout
    path: delete-hpa-checkout.yaml
  - target:
      group: autoscaling
      version: v2
      kind: HorizontalPodAutoscaler
      name: auth
    path: delete-hpa-auth.yaml
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: public-shopcloud
    path: patch-public-ingress.yaml
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: internal-admin
    path: delete-internal-admin-ingress.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: admin-web
    path: delete-admin-web-deployment.yaml
  - target:
      version: v1
      kind: Service
      name: admin-web
    path: delete-admin-web-service.yaml
images:
  - name: REPLACE_ME/shopcloud/customer-web
    newName: 338078971311.dkr.ecr.us-east-1.amazonaws.com/shopcloud/dev/frontend
    newTag: "37626e4"
  - name: REPLACE_ME/shopcloud/catalog
    newName: 338078971311.dkr.ecr.us-east-1.amazonaws.com/shopcloud/dev/catalog
    newTag: 3d340bd
  - name: REPLACE_ME/shopcloud/cart
    newName: 338078971311.dkr.ecr.us-east-1.amazonaws.com/shopcloud/dev/cart
    newTag: 3d340bd
  - name: REPLACE_ME/shopcloud/checkout
    newName: 338078971311.dkr.ecr.us-east-1.amazonaws.com/shopcloud/dev/checkout
    newTag: dev-latest
  - name: REPLACE_ME/shopcloud/auth
    newName: 338078971311.dkr.ecr.us-east-1.amazonaws.com/shopcloud/dev/auth
    newTag: dev-latest
  - name: REPLACE_ME/shopcloud/admin
    newName: 338078971311.dkr.ecr.us-east-1.amazonaws.com/shopcloud/dev/admin
    newTag: dev-latest
replicas:
  - name: customer-web
    count: 1
  - name: catalog
    count: 1
  - name: cart
    count: 1
  - name: checkout
    count: 1
  - name: auth
    count: 1
  - name: admin
    count: 1
