apiVersion: v1
kind: ConfigMap
metadata:
  name: shopcloud-config
  namespace: shopcloud
data:
  APP_ENV: dev
  CORS_ORIGINS: https://dev.shopcloud.example.com,https://admin.dev.shopcloud.example.com
  ADMIN_CORS_ORIGINS: https://admin.dev.shopcloud.example.com
  NEXT_PUBLIC_CATALOG_URL: https://api.dev.shopcloud.example.com
  NEXT_PUBLIC_CART_URL: https://api.dev.shopcloud.example.com
  NEXT_PUBLIC_CHECKOUT_URL: https://api.dev.shopcloud.example.com
  NEXT_PUBLIC_AUTH_URL: https://api.dev.shopcloud.example.com
  NEXT_PUBLIC_ADMIN_URL: https://admin-api.dev.shopcloud.internal
