apiVersion: v1
kind: ServiceAccount
metadata:
  name: shopcloud-checkout
  namespace: shopcloud
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::338078971311:role/shopcloud-dev-checkout-sqs
