apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout
  namespace: shopcloud
spec:
  template:
    spec:
      containers:
        - name: checkout
          env:
            - name: JWT_VERIFIER
              value: "cognito"
            - name: COGNITO_REGION
              value: "us-east-1"
            - name: COGNITO_CUSTOMER_POOL_ID
              value: "us-east-1_ML4GVS8pk"
            - name: COGNITO_CUSTOMER_CLIENT_ID
              value: "s6uarb38gsig7gvdpd23v9e5t"
            - name: COGNITO_ADMIN_POOL_ID
              value: "us-east-1_UullAvJJ1"
            - name: COGNITO_ADMIN_CLIENT_ID
              value: "admin-local-not-enabled"
