apiVersion: v1
kind: ConfigMap
metadata:
  name: shopcloud-config
  namespace: shopcloud
data:
  APP_ENV: dev
  CORS_ORIGINS: "*"
  ADMIN_CORS_ORIGINS: "*"
  QUEUE_BACKEND: local
  STORAGE_BACKEND: local
  MAIL_BACKEND: local
  NEXT_PUBLIC_CATALOG_URL: ""
  NEXT_PUBLIC_CART_URL: ""
  NEXT_PUBLIC_CHECKOUT_URL: ""
  NEXT_PUBLIC_AUTH_URL: ""
  NEXT_PUBLIC_ADMIN_URL: ""
