- op: replace
  path: /metadata/annotations
  value:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/success-codes: "200-404"
    alb.ingress.kubernetes.io/group.name: public-shopcloud
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
- op: replace
  path: /spec/rules
  value:
    - http:
        paths:
          - path: /catalog
            pathType: Prefix
            backend:
              service:
                name: catalog
                port:
                  number: 8001
          - path: /api/cart
            pathType: Prefix
            backend:
              service:
                name: cart
                port:
                  number: 8002
          - path: /api/wishlist
            pathType: Prefix
            backend:
              service:
                name: cart
                port:
                  number: 8002
          - path: /checkout
            pathType: Prefix
            backend:
              service:
                name: checkout
                port:
                  number: 8003
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: auth
                port:
                  number: 8004
          - path: /
            pathType: Prefix
            backend:
              service:
                name: customer-web
                port:
                  number: 80
